### ISSUE TITLE
Not working on phonegap

### ISSUE THREAD

**Issue by Kae2312** [rmm5t/jquery-timeago#211]
Hi,

First of all it's nice lib, it works perfectly on browser ! 
But I'm trying to use it with cordova / phonegap but it's not working at all. It changes nothing.

Anyone else have tried to use timeago with PhoneGap / Cordova?

Thanks !

**Comment by rmm5t** [comment]
Sorry. Please ask questions like this on a site like [StackOverflow](http://stackoverflow.com/) instead. GitHub Issues have a different purpose.

With that said, I know little about PhoneGap/Cordova, but my guess is that you're trying to load your phonegap app with `document.ready` instead of `deviceready`:

http://stackoverflow.com/questions/12576062/jquery-document-ready-vs-phonegap-deviceready
