### ISSUE TITLE
Doesn't work with a Date object

### ISSUE THREAD

**Issue by perich** [rmm5t/jquery-timeago#246]
My project stores dates a ```new Date()```, but they don't work with this code

```<abbr class="timeago" title="<%= Date.now() %>Z"><%= Date.now() %></abbr>``` does not render, but the example code: ```<abbr class="timeago" title="2008-07-17T09:24:17Z">July 17, 2008</abbr>``` does.

**Comment by rmm5t** [comment]
Please [read the docs](http://timeago.yarp.com/) and understand how to format timestamps in Ruby and in general. ISO 8601 is an absolute requirement for this library.

The docs even provide a helper function that you can use. See the bottom of the docs.

There's also a rails-timeago asset gem that you can use. It also includes a helper method.

Or try this to mimic the basic intent of your example:

```erb
<abbr class="timeago" title="<%= Time.now.getutc.iso8601 %></abbr>
```

**Comment by perich** [comment]
@rmm5t 

I'd rather not use Ruby as it's not a Ruby project. What native JS object will this library work with. Clearly not Date.

**Comment by rmm5t** [comment]
> I'd rather not use Ruby as it's not a Ruby project. 

Sorry. Please ask questions like this on a site like [StackOverflow](http://stackoverflow.com/) or [Codementor.io](https://www.codementor.io/) instead. GitHub Issues have a different purpose, and it's unlikely anyone will find the time to help debug your issue here (or teach you how different languages and libraries work).

> What native JS object will this library work with. Clearly not Date.

Did you read the docs or any docs? Clearly not. JavaScript has a `Date` object just like Ruby has a `Date` class.

* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
* http://www.w3schools.com/jsref/jsref_toisostring.asp

If you have access to the DOM, the `timeago` library can also accept an instance of a javascript `Date`. It also accepts storing raw data on the timestamp DOM element under the `"timeago"` key instead of assigning a timestamp to the `title` attribute on `abbr` elements or the `datetime` attribute on `time` elements.  For example.

```javascript
$("#some-id").data("timeago", { datetime: new Date() });
```
