### ISSUE TITLE
Output result seems to be wrong

### ISSUE THREAD

**Issue by charlesmudy** [rmm5t/jquery-timeago#265]
I have formated my PHP to output this:
`<time class="timeago" datetime="2016-01-11T17:26:03Z" title="January 11, 2016">about an hour ago</time>`. It keeps saying "about an hour ago" even if the comment is new.

Any idea please?

**Comment by rmm5t** [comment]
Are you sure you've initialized the jquery snippet correctly? Any javascript errors in the console? 
http://timeago.yarp.com/

Sorry. I have to close this out. Please ask questions like this on a site like [StackOverflow](http://stackoverflow.com/) instead. GitHub Issues have a different purpose, and it's unlikely anyone will find the time to help debug your issue here.
