### ISSUE TITLE
[Authorize] About the website (timeago.org) code

### ISSUE THREAD

**Issue by hustcc** [rmm5t/jquery-timeago#305]
I open a project which is detached  from my work. 

The website is [here](http://timeago.org/). code saved from [http://timeago.yarp.com/](http://timeago.yarp.com/), and I add the code source [here](https://github.com/hustcc/timeago.js/blob/a0f872529bdec6ef7a8e340a567b8bcf73b48cb6/index.html#L135-L139).

The website caused controversy, so `open the issue for authorize`, if not, I will remove it.

**Comment by rmm5t** [comment]
Thanks for chiming in here. My project is MIT licensed. Officially, you can copy it for your own use however you want; however, the way you went about it is likely the reason you had so much controversy.  

I also just commented on the Reddit post that blew up a bit:
https://www.reddit.com/r/javascript/comments/51lgh3/timeagojs_a_tiny2kb_library_used_to_format_date/d7f4bzb

1. Copying the name exactly is very much disingenuous.
2. Not **linking** back to the original (my) project in both your documentation and the README and giving credit where credit was due is also disingenuous.
3. Copying the theme of the documentation pages exactly only adds confusion. 

However, with all that said, you were well within your rights according to the MIT license. Most people just see this behavior as likely smarmy, which is why you received so much backlash. 

Things that would help here:

1. I would really appreciate it if you changed the name of your project to something other than "Timeago."
2. I would appreciate it if you changed the general theme of your documentation site. 
3. I would appreciate it if you did not copy my logo for jquery-Timeago. Please create your own logo.
5. I would really appreciate it if you might consider selling the domain `timeago.org` to me.

**Comment by hustcc** [comment]
Thanks for your reply.
1. The project name is `timeago.js`, and the all people want to name there project with `appropriate meaning`, so named with `timeago.js` is OK.
2. I will change the website theme later.
3. The logo will be chanded, very sorry.
4. README will be updated
5. How much ? ^_^

Very thanks

**Comment by rmm5t** [comment]
> The project name is timeago.js, and the all people want to name there project with appropriate meaning, so named with timeago.js is OK.

No. It's really not ok. At a minimum, it's NOT cool. This is likely the main and most important point of contention. Had you implemented timeago in another language, that'd be a different story, but because you chose the same name for the same underlying language, this is probably the main reason why you received so much backlash.

Suggestions for other names you could switch to:

* fuzzy time
* timestamp
* time machine
* time cache
* point in time
* one time
* time to time
* time before time
* ... I could go on and on with appropriate names.

> 5. How much [for] the domain ? ^_^

Please email me (email address on my GitHub profile) if you're serious about selling it, but please don’t expect much profit from this. I'm only willing to compensate you for your time and hassle.

**Comment by rmm5t** [comment]
@hustcc Upon browsing your GitHub profile, I came across your [aTool-org](https://github.com/aTool-org) organization and associated avatar/logo. It looks like you blatantly copied [tumblr's logo](https://www.google.com/search?q=tumblr+logo&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjLvqnX9oLPAhUM7iYKHZONBpAQ_AUICCgB&biw=1680&bih=949).

![2016-09-09 12-35-32](https://cloud.githubusercontent.com/assets/740/18398427/ec1b60d2-7689-11e6-9142-e466951684c2.png)

Your behavior follows a pattern that will likely continue to get you in trouble. Copy-cats can be flattering but are usually less respected.

**Comment by hustcc** [comment]
I wrote [timeago](https://github.com/hustcc/timeago) firstly, a Python lib. then `timeago.js`, and later wrote [timeago-react](https://github.com/hustcc/timeago-react), base on timeago.js for react.

I will not write the 4th one, because: 

 - in front-end, `timeago.js` is enough,
 - in back-end, I only care the lib performace rather than the size(I am sorry to rerwite timeago for javascript because the size of jQuery).

----

About the atool-logo, I'am very sorry, It **was copied tumblr's logo**(I will remove it).

I am `Sincerely`, but you are `Full of banter`, and collect my mistake, are there `timeago.js` so much influence for you ?

Though I am a front-end starter, but never bow to a insincere great.

**Comment by rmm5t** [comment]
> I am Sincerely, but you are Full of banter 

1. `banter`:  [_"I Do Not Think It Means What You Think It Means"_](https://youtu.be/G2y8Sx4B2Sk) ... Well, maybe now it does.

> and collect my mistake, 

Plagiarism is usually frowned upon.

> are there timeago.js so much influence for you ?

I'm not the one who opened this issue, nor am I the one who complained that you created a competing project (a subreddit did), with the exact same name, and the exact same theme for a website. I think most people feel it's hard to believe you did all this sincerely.

You asked how you could make things right. I answered. If you're unwilling to make things right, that's your perogative, but I don't think you retain the right to question why a JS library named "timeago" would bother the community when the behavior mimics an existing library with the exact same name so closely.

> Though I am a front-end starter, but never bow to a insincere great.

I presume you meant "threat?" There have been zero threats that I've seen. I've merely offered you free advice. Again, your actions got you here. I'm just trying to help you dig out of the hole you dug for yourself. If you don't want to heed my advice, I'll stop wasting my time, but please don't expect to thrive in this industry with that kind of attitude.

**Comment by hustcc** [comment]
You win. KO~

I continue update my project, because I need it.

**Comment by hustcc** [comment]
I am sorry, after translated your post, I found I am too impulsive…

I want to close it.

**Comment by sutra** [comment]
> You win. KO~
> 
> I continue update my project, because I need it.
> 
> 我英文太差，说英文好累~

Chiense: 我认为你最好要把网站改了，特别是logo，和排版风格，这太容易混淆了。
English: I think you should redesign your website, and do not use the logo which copied from this project, and the flavor of the website, this is confuse.
