### ISSUE TITLE
'cutoff' Setting not working when using timeago programmatically 

### ISSUE THREAD

**Issue by alfeugds** [rmm5t/jquery-timeago#308]
The [cutoff](https://github.com/rmm5t/jquery-timeago#settings) setting doesn't work when using timeago programmatically.

See sample code below:

```
$(function() {
    jQuery("time.timeago").timeago();
		// Display original dates older than 24 hours
    var cutoff = 1000*60*60*24;
    jQuery.timeago.settings.cutoff = cutoff;
    $("abbr.timeago").timeago();
    
    var created_at = "2008-07-17T09:24:17Z";
		$('#hue').text(jQuery.timeago(new Date(created_at)));
});
```

[JSFiddle](http://jsfiddle.net/alfeugds/VQzrG/3/)

Am I doing something wrong?

Thanks!

**Comment by rmm5t** [comment]
You're right, it doesn't, but it's by design. The `cutoff` setting is for the proper jQuery plugin function only (`$(...).timeago()`).  

The  _"manual"_ `jQuery.timeago()` function is intended to just be a straight linguistic conversion. It's just something to access a bit of the internals of the jQuery plugin itself. It's up to you to program around it (for things like a "cutoff").
