### ISSUE TITLE
syntax problem in locale files 

### ISSUE THREAD

**Issue by ismcagdas** [rmm5t/jquery-timeago#321]
Hi,

I'm using jquery-timeago in an angular 4.x project with angular-cli.
Webpack script loader complains about ending semicolon in jquery-timeago's localization files.

For example, in jquery.timeago.en.js, when I add ) after } in line 9 here https://github.com/rmm5t/jquery-timeago/blob/master/locales/jquery.timeago.en.js#L9, this problem is fixed.

I'm not sure if the problem is related to jquery-timeago or webpack's script loader but I just wanted to ask here.

Thanks.

**Comment by rmm5t** [comment]
@m90 Do you have time to look into this?

**Comment by m90** [comment]
I can look into that later today, although I am unsure why that is to be honest as the syntax of the file is valid (https://jsfiddle.net/yu8aeptp/), and the plugin uses the same syntax in the main file: https://github.com/rmm5t/jquery-timeago/blob/master/jquery.timeago.js#L27. Which makes me think it's related to the build pipeline in this particular case.

I'll let you know if I can find out anything here.

**Comment by m90** [comment]
@rmm5t It looks to me as if this is due to the fact that #320 is not on npm yet. When I do a `npm install` in a fresh project I will install 1.6.0 including the broken definitions. When I manually install master (i.e. `git+https://github.com/rmm5t/jquery-timeago#master`) I can bundle the locales just as expected (I'm doing that using browserify, but I guess that makes no difference here).

**Comment by m90** [comment]
@ismcagdas Did you install the package using `npm` or something similar? In case yes, when did you do that?

**Comment by rmm5t** [comment]
😞 Sorry. So true. I forgot to run my `publish` script. 

v1.6.1 is now published to NPM.

**Comment by ismcagdas** [comment]
@m90, @rmm5t I have tried v1.6.1 and it is fixed.
Thanks a lot for quick response and this great library 😄
