### ISSUE TITLE
How to deal with the time zone difference

### ISSUE THREAD

**Issue by BoumBam** [rmm5t/jquery-timeago#361]
Using mysql, in a post table I use `UTC_TIMESTAMP()` to store the date_time of publication.

Everything was ok when I was working on wampserver on local.

But I hosted my site yesterday on a server located in France, 2 hours away from the time zone of my country.

After posting, I see "2 hours ago" when I just published 30 seconds ago.

How can I take into account the time zone of my users compared to the timestamp from database ?

Sample: If I post a content, 30 seconds later Me and the user who is at china or anywhere must see "30 seconds ago".

I tried that:
 `  
  <time class="DateTime" datetime="<?= date(DATE_ISO8601, strtotime('2020-03-05 09:00:31 +0700')) ?>"></time>`
When my local UTC timezone offset is `+7`,  and time is   `2020-03-05 16:00:31`
 instead of giving me  "a few seconds ago", It gives me "7 hours ago".

Thank you.

**Comment by DanielDanielDanielD** [comment]
Hi, I'm now having the exact same problem, have you found any solution to this?

**Comment by BoumBam** [comment]
@DanielDanielDanielD 
It is not a problem with jquery-timeago.

It is with php.

Here is how I did:

`<time  class='timeago' datetime='".date(DATE_ISO8601,  strtotime($date); )."'></time>;`

**$date** is a DATE_TIME.

Sorry for the late answer

**Comment by DanielDanielDanielD** [comment]
Hi, thanks for your reply,

Your answer is still relevant because I have not yet found a solution to the problem.
I am currently working on a solution through moment.js timezone but also without success.

My project was built in a .NET environment but I believe it should not interfere with reading the date and time, can you please tell me in what format your date and time come from the database?

**Comment by BoumBam** [comment]
MY
I used mysql function `UTC_TIMESTAMP()` to store the dateTime.

like that: **2009-12-01 00:00:00**.

**Comment by DanielDanielDanielD** [comment]
Thanks for the help, I just found an answer to this :)

Since in my website the timezone is per content posted on the website and not per user timezone then I had to add to each message on the website a timezone signature in DB, then calculate with the moment.js timezone directory when it is created anywhere according to the customer's timezone.

I got this answer through here: https://stackoverflow.com/q/65461333/7074256

**Comment by rmm5t** [comment]
@BoumBam is correct. You must format your time stamp into ISO8601 format for timeago to work. This is pretty standard for any type of library like this.
