### ISSUE TITLE
A way to destroy/unload timeago for elements removed from DOM?

### ISSUE THREAD

**Issue by mikl** [rmm5t/jquery-timeago#40]
If you have a document that changes a lot, where elements are added and removed on the fly, it would be nice to have a way to clean out timeago instances bound to removed dom elements, so their timers stop firing, etc.

**Comment by jasondavis** [comment]
I need this exact feature.  

I open up "Project Task records" into a single Modal DIV in the DOM.  Each Task record that is clicked on, loads it;s Tsk Data into the Modal DIV. 

When a Task Modal is opened, I would like to setup and run the time ago on a "Due Date" DAteTime in my Task Modal.

When the Task Modal is closed, I need to clear/destroy it!  So that when the next Task Modal is opened, it does not have the value from thew previous task still running in the background.

Has a solution for this been released yet?

**Comment by rmm5t** [comment]
Sorry this has been open so long. Two features are part of timeago since this Issue was opened:

1. If you pass `"dispose"` to the timeago function, it will clear all associated timers thereby destroying/unloading.
2. If an DOM element no longer exists, the timer is auto-destroyed. See #190.
